export const GET_RESTAURANT = 'GET_RESTAURANT';
export const SET_RATING = 'SET_RATING';
export const SET_RESERVATION = 'SET_RESERVATION';
export const EDIT_RESTAURANT = 'EDIT_RESTAURANT'
export const GET_ALL_RESTAURANTS = 'GET_ALL_RESTAURANTS';
export const SET_VISIBLE_WORDS = 'SET_VISIBLE_WORDS';
export const GET_RESTAURANTS_BY_COORD = 'GET_RESTAURANTS_BY_COORD';
