export const SELECT_OPTION = 'SELECT_OPTION'
export const SEARCH_OPTION = 'SEARCH_OPTION'
export const SET_RESTS = 'SET_RESTS'
export const GET_RESTS = 'GET_RESTS'
export const GET_RESTAURANTS_BY_COORD = 'GET_RESTAURANTS_BY_COORD';
